// Rich visual theme system for strategy decks.
// Each theme combines:
//   - palette: color set (bg / coverBg / text / muted / accent / accent2)
//             plus gradient and depth tokens (coverGradient / bgGradient /
//             accentGradient / cardBg / cardBorder / glow)
//   - coverStyle: how cover slides are laid out (~16 variants)
//   - contentStyle: how content slides are laid out (~16 variants)
//   - typography: title and body font + sizes
// 55 themes generated by combining these dimensions.

export type Palette = {
  bg: string;
  bgAlt: string;             // soft variant of bg (for half-color, blocks)
  bgGradient: string;        // subtle gradient for content slide backgrounds
  coverBg: string;           // fallback solid cover bg
  coverGradient: string;     // rich multi-stop gradient for cover/section
  coverText: string;
  text: string;
  textMuted: string;
  accent: string;
  accent2: string;
  accentGradient: string;    // gradient for accent bars/elements
  cardBg: string;            // bg for content cards (with subtle alpha)
  cardBorder: string;        // border color for cards
  glow: string;              // soft glow color (rgba) for hero elements
  dark: boolean;
};

export type PaletteId =
  | "corporate-navy"
  | "midnight-violet"
  | "deep-forest"
  | "wine"
  | "obsidian"
  | "tech-cyan"
  | "muted-slate"
  | "soft-cream"
  | "minimal-paper"
  | "warm-terracotta"
  | "fresh-green"
  | "blush"
  | "monochrome"
  | "earth"
  | "arctic"
  | "sunset"
  | "royal-purple"
  | "emerald"
  | "crimson"
  | "ocean-teal"
  | "amber-gold"
  | "rose-mauve"
  | "indigo-night"
  | "sage"
  | "graphite"
  | "coral-reef"
  | "plum-wine"
  | "steel-blue"
  | "mint-fresh"
  | "burnt-sienna";

export const PALETTES: Record<PaletteId, Palette> = {
  "corporate-navy": {
    bg: "#ffffff", bgAlt: "#f0f4fa",
    bgGradient: "linear-gradient(180deg, #ffffff 0%, #f1f5fb 100%)",
    coverBg: "#0b2e54",
    coverGradient: "linear-gradient(135deg, #050f24 0%, #0b2e54 45%, #1a4275 100%)",
    coverText: "#ffffff",
    text: "#0b1e3a", textMuted: "#4b5e7a",
    accent: "#d4a23a", accent2: "#2a6db5",
    accentGradient: "linear-gradient(90deg, #d4a23a 0%, #b88a2e 100%)",
    cardBg: "rgba(11,46,84,0.04)",
    cardBorder: "rgba(11,46,84,0.12)",
    glow: "rgba(212,162,58,0.22)",
    dark: false,
  },
  "midnight-violet": {
    bg: "#0e0a1f", bgAlt: "#1a1238",
    bgGradient: "linear-gradient(160deg, #0e0a1f 0%, #1a1038 100%)",
    coverBg: "#1a0a3d",
    coverGradient: "linear-gradient(135deg, #1a0a3d 0%, #4a1a8a 55%, #7c3aed 100%)",
    coverText: "#ffffff",
    text: "#e9e3ff", textMuted: "#9c8bd1",
    accent: "#b794f4", accent2: "#7c5cff",
    accentGradient: "linear-gradient(90deg, #b794f4 0%, #7c5cff 100%)",
    cardBg: "rgba(183,148,244,0.10)",
    cardBorder: "rgba(183,148,244,0.22)",
    glow: "rgba(183,148,244,0.32)",
    dark: true,
  },
  "deep-forest": {
    bg: "#0d1f17", bgAlt: "#16332a",
    bgGradient: "linear-gradient(160deg, #0d1f17 0%, #16332a 100%)",
    coverBg: "#0a3a25",
    coverGradient: "linear-gradient(135deg, #03150d 0%, #0a3a25 50%, #1a6a48 100%)",
    coverText: "#ffffff",
    text: "#dceee2", textMuted: "#7fb29a",
    accent: "#5dd39e", accent2: "#facc15",
    accentGradient: "linear-gradient(90deg, #5dd39e 0%, #2da874 100%)",
    cardBg: "rgba(93,211,158,0.10)",
    cardBorder: "rgba(93,211,158,0.22)",
    glow: "rgba(93,211,158,0.28)",
    dark: true,
  },
  "wine": {
    bg: "#1f0a10", bgAlt: "#321a23",
    bgGradient: "linear-gradient(160deg, #1f0a10 0%, #321a23 100%)",
    coverBg: "#5d1a28",
    coverGradient: "linear-gradient(135deg, #2b0610 0%, #5d1a28 55%, #8a2a3d 100%)",
    coverText: "#ffffff",
    text: "#f6dde4", textMuted: "#c89aa7",
    accent: "#e8b04b", accent2: "#f56565",
    accentGradient: "linear-gradient(90deg, #e8b04b 0%, #c98a2a 100%)",
    cardBg: "rgba(232,176,75,0.10)",
    cardBorder: "rgba(232,176,75,0.22)",
    glow: "rgba(232,176,75,0.26)",
    dark: true,
  },
  "obsidian": {
    bg: "#0a0a0a", bgAlt: "#1c1c1c",
    bgGradient: "linear-gradient(160deg, #050505 0%, #131313 100%)",
    coverBg: "#000000",
    coverGradient: "radial-gradient(ellipse at 30% 30%, #1a1a1a 0%, #000000 70%)",
    coverText: "#ffffff",
    text: "#f4f4f4", textMuted: "#a0a0a0",
    accent: "#facc15", accent2: "#ef4444",
    accentGradient: "linear-gradient(90deg, #facc15 0%, #f59e0b 100%)",
    cardBg: "rgba(250,204,21,0.08)",
    cardBorder: "rgba(250,204,21,0.22)",
    glow: "rgba(250,204,21,0.28)",
    dark: true,
  },
  "tech-cyan": {
    bg: "#03101e", bgAlt: "#0c1f33",
    bgGradient: "linear-gradient(160deg, #03101e 0%, #0a1d33 100%)",
    coverBg: "#021022",
    coverGradient: "linear-gradient(135deg, #02091a 0%, #082c52 55%, #0d5a8a 100%)",
    coverText: "#ffffff",
    text: "#cfe9ff", textMuted: "#5b91b8",
    accent: "#22d3ee", accent2: "#a78bfa",
    accentGradient: "linear-gradient(90deg, #22d3ee 0%, #06b6d4 100%)",
    cardBg: "rgba(34,211,238,0.08)",
    cardBorder: "rgba(34,211,238,0.22)",
    glow: "rgba(34,211,238,0.28)",
    dark: true,
  },
  "muted-slate": {
    bg: "#1e293b", bgAlt: "#293547",
    bgGradient: "linear-gradient(160deg, #1e293b 0%, #2a3a52 100%)",
    coverBg: "#0f172a",
    coverGradient: "linear-gradient(135deg, #060b18 0%, #0f172a 50%, #1f2d4a 100%)",
    coverText: "#f1f5f9",
    text: "#f1f5f9", textMuted: "#94a3b8",
    accent: "#38bdf8", accent2: "#fbbf24",
    accentGradient: "linear-gradient(90deg, #38bdf8 0%, #0284c7 100%)",
    cardBg: "rgba(56,189,248,0.08)",
    cardBorder: "rgba(56,189,248,0.22)",
    glow: "rgba(56,189,248,0.26)",
    dark: true,
  },
  "soft-cream": {
    bg: "#fdf8f0", bgAlt: "#f5edd9",
    bgGradient: "linear-gradient(180deg, #fdf8f0 0%, #f6efe0 100%)",
    coverBg: "#3a2b1a",
    coverGradient: "linear-gradient(135deg, #21160a 0%, #3a2b1a 50%, #5e4528 100%)",
    coverText: "#fcecd0",
    text: "#3a2b1a", textMuted: "#7e6a52",
    accent: "#c97a3e", accent2: "#5a8a5e",
    accentGradient: "linear-gradient(90deg, #c97a3e 0%, #a25a26 100%)",
    cardBg: "rgba(201,122,62,0.08)",
    cardBorder: "rgba(201,122,62,0.20)",
    glow: "rgba(201,122,62,0.22)",
    dark: false,
  },
  "minimal-paper": {
    bg: "#ffffff", bgAlt: "#f7f7f7",
    bgGradient: "linear-gradient(180deg, #ffffff 0%, #f8f8f8 100%)",
    coverBg: "#111111",
    coverGradient: "linear-gradient(135deg, #000000 0%, #111111 50%, #2a2a2a 100%)",
    coverText: "#ffffff",
    text: "#111111", textMuted: "#666666",
    accent: "#111111", accent2: "#dc2626",
    accentGradient: "linear-gradient(90deg, #111111 0%, #444444 100%)",
    cardBg: "rgba(17,17,17,0.04)",
    cardBorder: "rgba(17,17,17,0.12)",
    glow: "rgba(220,38,38,0.18)",
    dark: false,
  },
  "warm-terracotta": {
    bg: "#fff7ef", bgAlt: "#ffe9d8",
    bgGradient: "linear-gradient(180deg, #fff7ef 0%, #fce6d2 100%)",
    coverBg: "#9c3a1a",
    coverGradient: "linear-gradient(135deg, #4e1a08 0%, #9c3a1a 55%, #d65a2a 100%)",
    coverText: "#ffffff",
    text: "#4a1a08", textMuted: "#a3573a",
    accent: "#e0531a", accent2: "#1d6d62",
    accentGradient: "linear-gradient(90deg, #e0531a 0%, #b53a0a 100%)",
    cardBg: "rgba(224,83,26,0.08)",
    cardBorder: "rgba(224,83,26,0.20)",
    glow: "rgba(224,83,26,0.24)",
    dark: false,
  },
  "fresh-green": {
    bg: "#f0faf4", bgAlt: "#dcf2e3",
    bgGradient: "linear-gradient(180deg, #f0faf4 0%, #d6efe0 100%)",
    coverBg: "#0f4d2e",
    coverGradient: "linear-gradient(135deg, #03210f 0%, #0f4d2e 50%, #1e7a47 100%)",
    coverText: "#ffffff",
    text: "#0e2d1d", textMuted: "#3d6b51",
    accent: "#0f9d58", accent2: "#fbbf24",
    accentGradient: "linear-gradient(90deg, #0f9d58 0%, #07733e 100%)",
    cardBg: "rgba(15,157,88,0.08)",
    cardBorder: "rgba(15,157,88,0.20)",
    glow: "rgba(15,157,88,0.22)",
    dark: false,
  },
  "blush": {
    bg: "#fff5f7", bgAlt: "#fde0e6",
    bgGradient: "linear-gradient(180deg, #fff5f7 0%, #fbdde4 100%)",
    coverBg: "#a83248",
    coverGradient: "linear-gradient(135deg, #4d0e1c 0%, #a83248 50%, #d8536e 100%)",
    coverText: "#ffffff",
    text: "#4a0e1c", textMuted: "#a4677a",
    accent: "#e94668", accent2: "#1a4a8a",
    accentGradient: "linear-gradient(90deg, #e94668 0%, #b8264a 100%)",
    cardBg: "rgba(233,70,104,0.08)",
    cardBorder: "rgba(233,70,104,0.20)",
    glow: "rgba(233,70,104,0.24)",
    dark: false,
  },
  "monochrome": {
    bg: "#f2f2f2", bgAlt: "#e0e0e0",
    bgGradient: "linear-gradient(180deg, #f2f2f2 0%, #e8e8e8 100%)",
    coverBg: "#1a1a1a",
    coverGradient: "linear-gradient(135deg, #000000 0%, #1a1a1a 50%, #3a3a3a 100%)",
    coverText: "#ffffff",
    text: "#1a1a1a", textMuted: "#606060",
    accent: "#1a1a1a", accent2: "#909090",
    accentGradient: "linear-gradient(90deg, #1a1a1a 0%, #4a4a4a 100%)",
    cardBg: "rgba(26,26,26,0.05)",
    cardBorder: "rgba(26,26,26,0.14)",
    glow: "rgba(26,26,26,0.18)",
    dark: false,
  },
  "earth": {
    bg: "#f5efe6", bgAlt: "#e6d9c2",
    bgGradient: "linear-gradient(180deg, #f5efe6 0%, #e8dcc6 100%)",
    coverBg: "#3d2914",
    coverGradient: "linear-gradient(135deg, #1f140a 0%, #3d2914 50%, #6a4b28 100%)",
    coverText: "#f5efe6",
    text: "#3d2914", textMuted: "#7a5f44",
    accent: "#a86f2d", accent2: "#4c6b3a",
    accentGradient: "linear-gradient(90deg, #a86f2d 0%, #7a4f1c 100%)",
    cardBg: "rgba(168,111,45,0.08)",
    cardBorder: "rgba(168,111,45,0.20)",
    glow: "rgba(168,111,45,0.22)",
    dark: false,
  },
  "arctic": {
    bg: "#f0f9ff", bgAlt: "#dcedf9",
    bgGradient: "linear-gradient(180deg, #f0f9ff 0%, #dceffb 100%)",
    coverBg: "#0c3e5a",
    coverGradient: "linear-gradient(135deg, #04162a 0%, #0c3e5a 50%, #1e6da0 100%)",
    coverText: "#ffffff",
    text: "#0c2438", textMuted: "#5a7a96",
    accent: "#0284c7", accent2: "#06b6d4",
    accentGradient: "linear-gradient(90deg, #0284c7 0%, #06b6d4 100%)",
    cardBg: "rgba(2,132,199,0.08)",
    cardBorder: "rgba(2,132,199,0.20)",
    glow: "rgba(2,132,199,0.24)",
    dark: false,
  },
  "sunset": {
    bg: "#fff8ec", bgAlt: "#ffe6c4",
    bgGradient: "linear-gradient(180deg, #fff8ec 0%, #ffe2c0 100%)",
    coverBg: "#7c2d12",
    coverGradient: "linear-gradient(135deg, #4a0e08 0%, #b8341e 35%, #f97316 70%, #e11d48 100%)",
    coverText: "#ffffff",
    text: "#3a1408", textMuted: "#8a5a3c",
    accent: "#f97316", accent2: "#e11d48",
    accentGradient: "linear-gradient(90deg, #f97316 0%, #e11d48 100%)",
    cardBg: "rgba(249,115,22,0.08)",
    cardBorder: "rgba(249,115,22,0.22)",
    glow: "rgba(249,115,22,0.28)",
    dark: false,
  },

  // ── 14 additional palettes — varied hues, light & dark ──
  "royal-purple": {
    bg: "#ffffff", bgAlt: "#f3eefc",
    bgGradient: "linear-gradient(180deg, #ffffff 0%, #f4eefb 100%)",
    coverBg: "#3b0764",
    coverGradient: "linear-gradient(135deg, #2e0552 0%, #6d28d9 55%, #a855f7 100%)",
    coverText: "#ffffff",
    text: "#2a1248", textMuted: "#6b5a86",
    accent: "#8b5cf6", accent2: "#c026d3",
    accentGradient: "linear-gradient(90deg, #8b5cf6 0%, #c026d3 100%)",
    cardBg: "rgba(139,92,246,0.07)", cardBorder: "rgba(139,92,246,0.2)", glow: "rgba(139,92,246,0.28)",
    dark: false,
  },
  "emerald": {
    bg: "#f3fbf6", bgAlt: "#dcf3e6",
    bgGradient: "linear-gradient(180deg, #f3fbf6 0%, #dcf3e6 100%)",
    coverBg: "#053d2c",
    coverGradient: "linear-gradient(135deg, #022c20 0%, #0f766e 55%, #10b981 100%)",
    coverText: "#ffffff",
    text: "#0a2e22", textMuted: "#4a6e60",
    accent: "#059669", accent2: "#0d9488",
    accentGradient: "linear-gradient(90deg, #059669 0%, #0d9488 100%)",
    cardBg: "rgba(5,150,105,0.07)", cardBorder: "rgba(5,150,105,0.2)", glow: "rgba(5,150,105,0.26)",
    dark: false,
  },
  "crimson": {
    bg: "#fff5f5", bgAlt: "#ffe0e0",
    bgGradient: "linear-gradient(180deg, #fff5f5 0%, #ffe0e0 100%)",
    coverBg: "#5e0a1e",
    coverGradient: "linear-gradient(135deg, #450713 0%, #9f1239 55%, #e11d48 100%)",
    coverText: "#ffffff",
    text: "#3d0a16", textMuted: "#8a5560",
    accent: "#dc2626", accent2: "#be123c",
    accentGradient: "linear-gradient(90deg, #dc2626 0%, #be123c 100%)",
    cardBg: "rgba(220,38,38,0.06)", cardBorder: "rgba(220,38,38,0.2)", glow: "rgba(220,38,38,0.26)",
    dark: false,
  },
  "ocean-teal": {
    bg: "#f0fbfd", bgAlt: "#cdeef4",
    bgGradient: "linear-gradient(180deg, #f0fbfd 0%, #cdeef4 100%)",
    coverBg: "#063b46",
    coverGradient: "linear-gradient(135deg, #042830 0%, #0e7490 55%, #06b6d4 100%)",
    coverText: "#ffffff",
    text: "#0a2e36", textMuted: "#456a72",
    accent: "#0891b2", accent2: "#0e7490",
    accentGradient: "linear-gradient(90deg, #0891b2 0%, #0e7490 100%)",
    cardBg: "rgba(8,145,178,0.07)", cardBorder: "rgba(8,145,178,0.2)", glow: "rgba(8,145,178,0.26)",
    dark: false,
  },
  "amber-gold": {
    bg: "#fffbeb", bgAlt: "#fdeec0",
    bgGradient: "linear-gradient(180deg, #fffbeb 0%, #fdeec0 100%)",
    coverBg: "#3f2d04",
    coverGradient: "linear-gradient(135deg, #2d2003 0%, #b45309 55%, #f59e0b 100%)",
    coverText: "#ffffff",
    text: "#3a2c08", textMuted: "#806a3a",
    accent: "#d97706", accent2: "#ca8a04",
    accentGradient: "linear-gradient(90deg, #d97706 0%, #ca8a04 100%)",
    cardBg: "rgba(217,119,6,0.08)", cardBorder: "rgba(217,119,6,0.22)", glow: "rgba(217,119,6,0.26)",
    dark: false,
  },
  "rose-mauve": {
    bg: "#fdf4f8", bgAlt: "#f8deea",
    bgGradient: "linear-gradient(180deg, #fdf4f8 0%, #f8deea 100%)",
    coverBg: "#500724",
    coverGradient: "linear-gradient(135deg, #3d0620 0%, #9d174d 55%, #db2777 100%)",
    coverText: "#ffffff",
    text: "#3f0f26", textMuted: "#8a5a72",
    accent: "#db2777", accent2: "#a21caf",
    accentGradient: "linear-gradient(90deg, #db2777 0%, #a21caf 100%)",
    cardBg: "rgba(219,39,119,0.06)", cardBorder: "rgba(219,39,119,0.2)", glow: "rgba(219,39,119,0.24)",
    dark: false,
  },
  "indigo-night": {
    bg: "#0f1226", bgAlt: "#1a1f3d",
    bgGradient: "linear-gradient(160deg, #0f1226 0%, #1a1f3d 100%)",
    coverBg: "#0b0e1f",
    coverGradient: "linear-gradient(135deg, #0b0e1f 0%, #312e81 55%, #4f46e5 100%)",
    coverText: "#ffffff",
    text: "#e3e6f5", textMuted: "#9095bf",
    accent: "#6366f1", accent2: "#818cf8",
    accentGradient: "linear-gradient(90deg, #6366f1 0%, #818cf8 100%)",
    cardBg: "rgba(99,102,241,0.12)", cardBorder: "rgba(99,102,241,0.25)", glow: "rgba(99,102,241,0.34)",
    dark: true,
  },
  "sage": {
    bg: "#f5f8f3", bgAlt: "#e3ecdc",
    bgGradient: "linear-gradient(180deg, #f5f8f3 0%, #e3ecdc 100%)",
    coverBg: "#2e3a2a",
    coverGradient: "linear-gradient(135deg, #20281d 0%, #4b5d43 55%, #84a06f 100%)",
    coverText: "#ffffff",
    text: "#2c352a", textMuted: "#65725e",
    accent: "#6b8e4e", accent2: "#557a46",
    accentGradient: "linear-gradient(90deg, #6b8e4e 0%, #557a46 100%)",
    cardBg: "rgba(107,142,78,0.08)", cardBorder: "rgba(107,142,78,0.22)", glow: "rgba(107,142,78,0.24)",
    dark: false,
  },
  "graphite": {
    bg: "#1a1c1e", bgAlt: "#26292c",
    bgGradient: "linear-gradient(160deg, #1a1c1e 0%, #26292c 100%)",
    coverBg: "#0e0f11",
    coverGradient: "linear-gradient(135deg, #0e0f11 0%, #2a2d31 60%, #475569 100%)",
    coverText: "#ffffff",
    text: "#e7eaed", textMuted: "#9aa1a8",
    accent: "#f59e0b", accent2: "#fbbf24",
    accentGradient: "linear-gradient(90deg, #f59e0b 0%, #fbbf24 100%)",
    cardBg: "rgba(255,255,255,0.05)", cardBorder: "rgba(255,255,255,0.12)", glow: "rgba(245,158,11,0.3)",
    dark: true,
  },
  "coral-reef": {
    bg: "#fff6f3", bgAlt: "#ffe1d6",
    bgGradient: "linear-gradient(180deg, #fff6f3 0%, #ffe1d6 100%)",
    coverBg: "#7c2618",
    coverGradient: "linear-gradient(135deg, #5a160c 0%, #ea580c 50%, #fb7185 100%)",
    coverText: "#ffffff",
    text: "#43170f", textMuted: "#8a5648",
    accent: "#f43f5e", accent2: "#fb7185",
    accentGradient: "linear-gradient(90deg, #f43f5e 0%, #fb923c 100%)",
    cardBg: "rgba(244,63,94,0.06)", cardBorder: "rgba(244,63,94,0.2)", glow: "rgba(244,63,94,0.24)",
    dark: false,
  },
  "plum-wine": {
    bg: "#1c1320", bgAlt: "#2a1d30",
    bgGradient: "linear-gradient(160deg, #1c1320 0%, #2a1d30 100%)",
    coverBg: "#120a16",
    coverGradient: "linear-gradient(135deg, #120a16 0%, #581c54 55%, #9d174d 100%)",
    coverText: "#ffffff",
    text: "#ecdff0", textMuted: "#a98fb0",
    accent: "#c084fc", accent2: "#e879b9",
    accentGradient: "linear-gradient(90deg, #c084fc 0%, #e879b9 100%)",
    cardBg: "rgba(192,132,252,0.1)", cardBorder: "rgba(192,132,252,0.22)", glow: "rgba(192,132,252,0.3)",
    dark: true,
  },
  "steel-blue": {
    bg: "#f4f7fa", bgAlt: "#dde7f0",
    bgGradient: "linear-gradient(180deg, #f4f7fa 0%, #dde7f0 100%)",
    coverBg: "#1e293b",
    coverGradient: "linear-gradient(135deg, #0f172a 0%, #334155 55%, #64748b 100%)",
    coverText: "#ffffff",
    text: "#1e2a3a", textMuted: "#5a6b7e",
    accent: "#2563eb", accent2: "#0ea5e9",
    accentGradient: "linear-gradient(90deg, #2563eb 0%, #0ea5e9 100%)",
    cardBg: "rgba(37,99,235,0.06)", cardBorder: "rgba(37,99,235,0.18)", glow: "rgba(37,99,235,0.24)",
    dark: false,
  },
  "mint-fresh": {
    bg: "#f0fdfa", bgAlt: "#cbf5ec",
    bgGradient: "linear-gradient(180deg, #f0fdfa 0%, #cbf5ec 100%)",
    coverBg: "#064e44",
    coverGradient: "linear-gradient(135deg, #033730 0%, #14b8a6 55%, #5eead4 100%)",
    coverText: "#ffffff",
    text: "#0c3b34", textMuted: "#4a7068",
    accent: "#14b8a6", accent2: "#2dd4bf",
    accentGradient: "linear-gradient(90deg, #14b8a6 0%, #2dd4bf 100%)",
    cardBg: "rgba(20,184,166,0.07)", cardBorder: "rgba(20,184,166,0.2)", glow: "rgba(20,184,166,0.24)",
    dark: false,
  },
  "burnt-sienna": {
    bg: "#fbf3ee", bgAlt: "#f0dccf",
    bgGradient: "linear-gradient(180deg, #fbf3ee 0%, #f0dccf 100%)",
    coverBg: "#3d1f12",
    coverGradient: "linear-gradient(135deg, #2b150b 0%, #9a3412 55%, #c2410c 100%)",
    coverText: "#ffffff",
    text: "#3a2317", textMuted: "#83604c",
    accent: "#c2410c", accent2: "#92400e",
    accentGradient: "linear-gradient(90deg, #c2410c 0%, #92400e 100%)",
    cardBg: "rgba(194,65,12,0.07)", cardBorder: "rgba(194,65,12,0.2)", glow: "rgba(194,65,12,0.24)",
    dark: false,
  },
};

// ─────────────────────── Layout variants ───────────────────────

export type CoverStyle =
  | "left-bar-strong"
  | "centered-bold"
  | "split-half"
  | "framed-thin"
  | "gradient-diagonal"
  | "minimal-bottom"
  | "big-number-corner"
  | "circle-accent"
  | "stripes-side"
  | "horizon-line"
  | "duotone-block"
  | "outlined-title"
  | "card-center"
  | "label-strip"
  | "geometric-corner"
  | "underline-title";

export type ContentStyle =
  | "classic-top"
  | "side-band"
  | "header-block"
  | "half-color"
  | "numbered-list"
  | "two-column"
  | "dot-grid"
  | "framed"
  | "footer-band"
  | "minimal-line"
  | "magazine"
  | "circle-bullets"
  | "stripe-cards"
  | "corner-accent"
  | "left-rule"
  | "card-stack";

// ─────────────────────── Typography ───────────────────────

export type FontPair = {
  display: string;
  body: string;
  pptxDisplay: string;
  pptxBody: string;
  letterSpacing?: string;
  titleWeight?: number;
};

export const FONT_PAIRS: Record<string, FontPair> = {
  classic:   { display: "Georgia, 'David Libre', serif", body: "'David Libre', Georgia, serif", pptxDisplay: "Georgia", pptxBody: "David", titleWeight: 700 },
  modern:    { display: "'Helvetica Neue', Arial, sans-serif", body: "'Helvetica Neue', Arial, sans-serif", pptxDisplay: "Calibri", pptxBody: "Calibri", titleWeight: 700 },
  editorial: { display: "Georgia, 'Frank Ruhl Libre', serif", body: "'Frank Ruhl Libre', Georgia, serif", pptxDisplay: "Georgia", pptxBody: "Frank Ruhl Libre", titleWeight: 700 },
  tech:      { display: "'Helvetica Neue', system-ui, sans-serif", body: "'Helvetica Neue', system-ui, sans-serif", pptxDisplay: "Calibri", pptxBody: "Calibri", letterSpacing: "-0.02em", titleWeight: 800 },
  elegant:   { display: "'Frank Ruhl Libre', Georgia, serif", body: "'Heebo', Arial, sans-serif", pptxDisplay: "Frank Ruhl Libre", pptxBody: "Heebo", titleWeight: 600 },
  bold:      { display: "'Heebo', Arial, sans-serif", body: "'Heebo', Arial, sans-serif", pptxDisplay: "Heebo", pptxBody: "Heebo", letterSpacing: "-0.01em", titleWeight: 900 },
  refined:   { display: "'Frank Ruhl Libre', serif", body: "'David Libre', serif", pptxDisplay: "Frank Ruhl Libre", pptxBody: "David", titleWeight: 600 },
  utility:   { display: "'Heebo', system-ui, sans-serif", body: "'David Libre', serif", pptxDisplay: "Heebo", pptxBody: "David", titleWeight: 700 },
};

export type FontPairId = keyof typeof FONT_PAIRS;

// ─────────────────────── Theme spec ───────────────────────

// Premium design systems (richer than the cover×content combinator).
// When `design` is set, the SlideView bypasses the cover/content router
// and renders via the named design — e.g. "editorial" routes every
// slide through designs/Editorial.tsx, which still reads palette+font
// from this theme so palette swaps still work.
export type DesignSystem =
  | "editorial" | "corporate" | "swiss" | "midnight" | "blueprint"
  | "sidebar" | "outline" | "strips" | "geometric" | "gradient";

export type DeckTheme = {
  id: string;
  name_he: string;
  name_en: string;
  palette: PaletteId;
  cover: CoverStyle;
  content: ContentStyle;
  font: FontPairId;
  titleScale?: number;
  bodyScale?: number;
  design?: DesignSystem;
};

// ─────────────────────── The 55 themes ───────────────────────

export const DECK_THEMES: DeckTheme[] = [
  // The single deck design — "Editorial". Colours come from the chosen
  // palette (via the palette picker), so this one design covers every
  // look; there are intentionally no other themes. `cover`/`content`/
  // `font` are unused by the editorial renderer but kept for type
  // compatibility.
  {
    id: "editorial",
    name_he: "Editorial",
    name_en: "Editorial",
    palette: "corporate-navy",
    cover: "minimal-bottom",
    content: "minimal-line",
    font: "editorial",
    design: "editorial",
  },
  {
    id: "corporate",
    name_he: "Corporate Cards",
    name_en: "Corporate Cards",
    palette: "corporate-navy",
    cover: "minimal-bottom",
    content: "minimal-line",
    font: "modern",
    design: "corporate",
  },
  { id: "swiss",     name_he: "Swiss Grid",  name_en: "Swiss Grid",  palette: "monochrome",      cover: "minimal-bottom", content: "minimal-line", font: "bold",   design: "swiss" },
  { id: "midnight",  name_he: "Midnight",    name_en: "Midnight",    palette: "obsidian",        cover: "minimal-bottom", content: "minimal-line", font: "tech",   design: "midnight" },
  { id: "blueprint", name_he: "Blueprint",   name_en: "Blueprint",   palette: "tech-cyan",       cover: "minimal-bottom", content: "minimal-line", font: "tech",   design: "blueprint" },
  { id: "sidebar",   name_he: "Sidebar",     name_en: "Sidebar",     palette: "corporate-navy",  cover: "minimal-bottom", content: "minimal-line", font: "modern", design: "sidebar" },
  { id: "outline",   name_he: "Outline",     name_en: "Outline",     palette: "monochrome",      cover: "minimal-bottom", content: "minimal-line", font: "modern", design: "outline" },
  { id: "strips",    name_he: "Strips",      name_en: "Strips",      palette: "warm-terracotta", cover: "minimal-bottom", content: "minimal-line", font: "bold",   design: "strips" },
  { id: "geometric", name_he: "Geometric",   name_en: "Geometric",   palette: "midnight-violet", cover: "minimal-bottom", content: "minimal-line", font: "bold",   design: "geometric" },
  { id: "gradient",  name_he: "Gradient",    name_en: "Gradient",    palette: "sunset",          cover: "minimal-bottom", content: "minimal-line", font: "modern", design: "gradient" },
];

// Convenience accessors

export function getTheme(id: string): DeckTheme {
  return DECK_THEMES.find((t) => t.id === id) ?? DECK_THEMES[0];
}

export function getPalette(p: PaletteId): Palette {
  return PALETTES[p];
}

export function getFont(id: FontPairId): FontPair {
  return FONT_PAIRS[id];
}

// Convert "#abcdef" → "abcdef" (no hash) for pptxgenjs
export function noHash(c: string): string {
  return c.startsWith("#") ? c.slice(1) : c;
}
