// Rich visual theme system for strategy decks.
// Each theme combines:
//   - palette: color set (bg / coverBg / text / muted / accent / accent2)
//             plus gradient and depth tokens (coverGradient / bgGradient /
//             accentGradient / cardBg / cardBorder / glow)
//   - coverStyle: how cover slides are laid out (~16 variants)
//   - contentStyle: how content slides are laid out (~16 variants)
//   - typography: title and body font + sizes
// 55 themes generated by combining these dimensions.

export type Palette = {
  bg: string;
  bgAlt: string;             // soft variant of bg (for half-color, blocks)
  bgGradient: string;        // subtle gradient for content slide backgrounds
  coverBg: string;           // fallback solid cover bg
  coverGradient: string;     // rich multi-stop gradient for cover/section
  coverText: string;
  text: string;
  textMuted: string;
  accent: string;
  accent2: string;
  accentGradient: string;    // gradient for accent bars/elements
  cardBg: string;            // bg for content cards (with subtle alpha)
  cardBorder: string;        // border color for cards
  glow: string;              // soft glow color (rgba) for hero elements
  dark: boolean;
};

export type PaletteId =
  | "corporate-navy"
  | "midnight-violet"
  | "deep-forest"
  | "wine"
  | "obsidian"
  | "tech-cyan"
  | "muted-slate"
  | "soft-cream"
  | "minimal-paper"
  | "warm-terracotta"
  | "fresh-green"
  | "blush"
  | "monochrome"
  | "earth"
  | "arctic"
  | "sunset";

export const PALETTES: Record<PaletteId, Palette> = {
  "corporate-navy": {
    bg: "#ffffff", bgAlt: "#f0f4fa",
    bgGradient: "linear-gradient(180deg, #ffffff 0%, #f1f5fb 100%)",
    coverBg: "#0b2e54",
    coverGradient: "linear-gradient(135deg, #050f24 0%, #0b2e54 45%, #1a4275 100%)",
    coverText: "#ffffff",
    text: "#0b1e3a", textMuted: "#4b5e7a",
    accent: "#d4a23a", accent2: "#2a6db5",
    accentGradient: "linear-gradient(90deg, #d4a23a 0%, #b88a2e 100%)",
    cardBg: "rgba(11,46,84,0.04)",
    cardBorder: "rgba(11,46,84,0.12)",
    glow: "rgba(212,162,58,0.22)",
    dark: false,
  },
  "midnight-violet": {
    bg: "#0e0a1f", bgAlt: "#1a1238",
    bgGradient: "linear-gradient(160deg, #0e0a1f 0%, #1a1038 100%)",
    coverBg: "#1a0a3d",
    coverGradient: "linear-gradient(135deg, #1a0a3d 0%, #4a1a8a 55%, #7c3aed 100%)",
    coverText: "#ffffff",
    text: "#e9e3ff", textMuted: "#9c8bd1",
    accent: "#b794f4", accent2: "#7c5cff",
    accentGradient: "linear-gradient(90deg, #b794f4 0%, #7c5cff 100%)",
    cardBg: "rgba(183,148,244,0.10)",
    cardBorder: "rgba(183,148,244,0.22)",
    glow: "rgba(183,148,244,0.32)",
    dark: true,
  },
  "deep-forest": {
    bg: "#0d1f17", bgAlt: "#16332a",
    bgGradient: "linear-gradient(160deg, #0d1f17 0%, #16332a 100%)",
    coverBg: "#0a3a25",
    coverGradient: "linear-gradient(135deg, #03150d 0%, #0a3a25 50%, #1a6a48 100%)",
    coverText: "#ffffff",
    text: "#dceee2", textMuted: "#7fb29a",
    accent: "#5dd39e", accent2: "#facc15",
    accentGradient: "linear-gradient(90deg, #5dd39e 0%, #2da874 100%)",
    cardBg: "rgba(93,211,158,0.10)",
    cardBorder: "rgba(93,211,158,0.22)",
    glow: "rgba(93,211,158,0.28)",
    dark: true,
  },
  "wine": {
    bg: "#1f0a10", bgAlt: "#321a23",
    bgGradient: "linear-gradient(160deg, #1f0a10 0%, #321a23 100%)",
    coverBg: "#5d1a28",
    coverGradient: "linear-gradient(135deg, #2b0610 0%, #5d1a28 55%, #8a2a3d 100%)",
    coverText: "#ffffff",
    text: "#f6dde4", textMuted: "#c89aa7",
    accent: "#e8b04b", accent2: "#f56565",
    accentGradient: "linear-gradient(90deg, #e8b04b 0%, #c98a2a 100%)",
    cardBg: "rgba(232,176,75,0.10)",
    cardBorder: "rgba(232,176,75,0.22)",
    glow: "rgba(232,176,75,0.26)",
    dark: true,
  },
  "obsidian": {
    bg: "#0a0a0a", bgAlt: "#1c1c1c",
    bgGradient: "linear-gradient(160deg, #050505 0%, #131313 100%)",
    coverBg: "#000000",
    coverGradient: "radial-gradient(ellipse at 30% 30%, #1a1a1a 0%, #000000 70%)",
    coverText: "#ffffff",
    text: "#f4f4f4", textMuted: "#a0a0a0",
    accent: "#facc15", accent2: "#ef4444",
    accentGradient: "linear-gradient(90deg, #facc15 0%, #f59e0b 100%)",
    cardBg: "rgba(250,204,21,0.08)",
    cardBorder: "rgba(250,204,21,0.22)",
    glow: "rgba(250,204,21,0.28)",
    dark: true,
  },
  "tech-cyan": {
    bg: "#03101e", bgAlt: "#0c1f33",
    bgGradient: "linear-gradient(160deg, #03101e 0%, #0a1d33 100%)",
    coverBg: "#021022",
    coverGradient: "linear-gradient(135deg, #02091a 0%, #082c52 55%, #0d5a8a 100%)",
    coverText: "#ffffff",
    text: "#cfe9ff", textMuted: "#5b91b8",
    accent: "#22d3ee", accent2: "#a78bfa",
    accentGradient: "linear-gradient(90deg, #22d3ee 0%, #06b6d4 100%)",
    cardBg: "rgba(34,211,238,0.08)",
    cardBorder: "rgba(34,211,238,0.22)",
    glow: "rgba(34,211,238,0.28)",
    dark: true,
  },
  "muted-slate": {
    bg: "#1e293b", bgAlt: "#293547",
    bgGradient: "linear-gradient(160deg, #1e293b 0%, #2a3a52 100%)",
    coverBg: "#0f172a",
    coverGradient: "linear-gradient(135deg, #060b18 0%, #0f172a 50%, #1f2d4a 100%)",
    coverText: "#f1f5f9",
    text: "#f1f5f9", textMuted: "#94a3b8",
    accent: "#38bdf8", accent2: "#fbbf24",
    accentGradient: "linear-gradient(90deg, #38bdf8 0%, #0284c7 100%)",
    cardBg: "rgba(56,189,248,0.08)",
    cardBorder: "rgba(56,189,248,0.22)",
    glow: "rgba(56,189,248,0.26)",
    dark: true,
  },
  "soft-cream": {
    bg: "#fdf8f0", bgAlt: "#f5edd9",
    bgGradient: "linear-gradient(180deg, #fdf8f0 0%, #f6efe0 100%)",
    coverBg: "#3a2b1a",
    coverGradient: "linear-gradient(135deg, #21160a 0%, #3a2b1a 50%, #5e4528 100%)",
    coverText: "#fcecd0",
    text: "#3a2b1a", textMuted: "#7e6a52",
    accent: "#c97a3e", accent2: "#5a8a5e",
    accentGradient: "linear-gradient(90deg, #c97a3e 0%, #a25a26 100%)",
    cardBg: "rgba(201,122,62,0.08)",
    cardBorder: "rgba(201,122,62,0.20)",
    glow: "rgba(201,122,62,0.22)",
    dark: false,
  },
  "minimal-paper": {
    bg: "#ffffff", bgAlt: "#f7f7f7",
    bgGradient: "linear-gradient(180deg, #ffffff 0%, #f8f8f8 100%)",
    coverBg: "#111111",
    coverGradient: "linear-gradient(135deg, #000000 0%, #111111 50%, #2a2a2a 100%)",
    coverText: "#ffffff",
    text: "#111111", textMuted: "#666666",
    accent: "#111111", accent2: "#dc2626",
    accentGradient: "linear-gradient(90deg, #111111 0%, #444444 100%)",
    cardBg: "rgba(17,17,17,0.04)",
    cardBorder: "rgba(17,17,17,0.12)",
    glow: "rgba(220,38,38,0.18)",
    dark: false,
  },
  "warm-terracotta": {
    bg: "#fff7ef", bgAlt: "#ffe9d8",
    bgGradient: "linear-gradient(180deg, #fff7ef 0%, #fce6d2 100%)",
    coverBg: "#9c3a1a",
    coverGradient: "linear-gradient(135deg, #4e1a08 0%, #9c3a1a 55%, #d65a2a 100%)",
    coverText: "#ffffff",
    text: "#4a1a08", textMuted: "#a3573a",
    accent: "#e0531a", accent2: "#1d6d62",
    accentGradient: "linear-gradient(90deg, #e0531a 0%, #b53a0a 100%)",
    cardBg: "rgba(224,83,26,0.08)",
    cardBorder: "rgba(224,83,26,0.20)",
    glow: "rgba(224,83,26,0.24)",
    dark: false,
  },
  "fresh-green": {
    bg: "#f0faf4", bgAlt: "#dcf2e3",
    bgGradient: "linear-gradient(180deg, #f0faf4 0%, #d6efe0 100%)",
    coverBg: "#0f4d2e",
    coverGradient: "linear-gradient(135deg, #03210f 0%, #0f4d2e 50%, #1e7a47 100%)",
    coverText: "#ffffff",
    text: "#0e2d1d", textMuted: "#3d6b51",
    accent: "#0f9d58", accent2: "#fbbf24",
    accentGradient: "linear-gradient(90deg, #0f9d58 0%, #07733e 100%)",
    cardBg: "rgba(15,157,88,0.08)",
    cardBorder: "rgba(15,157,88,0.20)",
    glow: "rgba(15,157,88,0.22)",
    dark: false,
  },
  "blush": {
    bg: "#fff5f7", bgAlt: "#fde0e6",
    bgGradient: "linear-gradient(180deg, #fff5f7 0%, #fbdde4 100%)",
    coverBg: "#a83248",
    coverGradient: "linear-gradient(135deg, #4d0e1c 0%, #a83248 50%, #d8536e 100%)",
    coverText: "#ffffff",
    text: "#4a0e1c", textMuted: "#a4677a",
    accent: "#e94668", accent2: "#1a4a8a",
    accentGradient: "linear-gradient(90deg, #e94668 0%, #b8264a 100%)",
    cardBg: "rgba(233,70,104,0.08)",
    cardBorder: "rgba(233,70,104,0.20)",
    glow: "rgba(233,70,104,0.24)",
    dark: false,
  },
  "monochrome": {
    bg: "#f2f2f2", bgAlt: "#e0e0e0",
    bgGradient: "linear-gradient(180deg, #f2f2f2 0%, #e8e8e8 100%)",
    coverBg: "#1a1a1a",
    coverGradient: "linear-gradient(135deg, #000000 0%, #1a1a1a 50%, #3a3a3a 100%)",
    coverText: "#ffffff",
    text: "#1a1a1a", textMuted: "#606060",
    accent: "#1a1a1a", accent2: "#909090",
    accentGradient: "linear-gradient(90deg, #1a1a1a 0%, #4a4a4a 100%)",
    cardBg: "rgba(26,26,26,0.05)",
    cardBorder: "rgba(26,26,26,0.14)",
    glow: "rgba(26,26,26,0.18)",
    dark: false,
  },
  "earth": {
    bg: "#f5efe6", bgAlt: "#e6d9c2",
    bgGradient: "linear-gradient(180deg, #f5efe6 0%, #e8dcc6 100%)",
    coverBg: "#3d2914",
    coverGradient: "linear-gradient(135deg, #1f140a 0%, #3d2914 50%, #6a4b28 100%)",
    coverText: "#f5efe6",
    text: "#3d2914", textMuted: "#7a5f44",
    accent: "#a86f2d", accent2: "#4c6b3a",
    accentGradient: "linear-gradient(90deg, #a86f2d 0%, #7a4f1c 100%)",
    cardBg: "rgba(168,111,45,0.08)",
    cardBorder: "rgba(168,111,45,0.20)",
    glow: "rgba(168,111,45,0.22)",
    dark: false,
  },
  "arctic": {
    bg: "#f0f9ff", bgAlt: "#dcedf9",
    bgGradient: "linear-gradient(180deg, #f0f9ff 0%, #dceffb 100%)",
    coverBg: "#0c3e5a",
    coverGradient: "linear-gradient(135deg, #04162a 0%, #0c3e5a 50%, #1e6da0 100%)",
    coverText: "#ffffff",
    text: "#0c2438", textMuted: "#5a7a96",
    accent: "#0284c7", accent2: "#06b6d4",
    accentGradient: "linear-gradient(90deg, #0284c7 0%, #06b6d4 100%)",
    cardBg: "rgba(2,132,199,0.08)",
    cardBorder: "rgba(2,132,199,0.20)",
    glow: "rgba(2,132,199,0.24)",
    dark: false,
  },
  "sunset": {
    bg: "#fff8ec", bgAlt: "#ffe6c4",
    bgGradient: "linear-gradient(180deg, #fff8ec 0%, #ffe2c0 100%)",
    coverBg: "#7c2d12",
    coverGradient: "linear-gradient(135deg, #4a0e08 0%, #b8341e 35%, #f97316 70%, #e11d48 100%)",
    coverText: "#ffffff",
    text: "#3a1408", textMuted: "#8a5a3c",
    accent: "#f97316", accent2: "#e11d48",
    accentGradient: "linear-gradient(90deg, #f97316 0%, #e11d48 100%)",
    cardBg: "rgba(249,115,22,0.08)",
    cardBorder: "rgba(249,115,22,0.22)",
    glow: "rgba(249,115,22,0.28)",
    dark: false,
  },
};

// ─────────────────────── Layout variants ───────────────────────

export type CoverStyle =
  | "left-bar-strong"
  | "centered-bold"
  | "split-half"
  | "framed-thin"
  | "gradient-diagonal"
  | "minimal-bottom"
  | "big-number-corner"
  | "circle-accent"
  | "stripes-side"
  | "horizon-line"
  | "duotone-block"
  | "outlined-title"
  | "card-center"
  | "label-strip"
  | "geometric-corner"
  | "underline-title";

export type ContentStyle =
  | "classic-top"
  | "side-band"
  | "header-block"
  | "half-color"
  | "numbered-list"
  | "two-column"
  | "dot-grid"
  | "framed"
  | "footer-band"
  | "minimal-line"
  | "magazine"
  | "circle-bullets"
  | "stripe-cards"
  | "corner-accent"
  | "left-rule"
  | "card-stack";

// ─────────────────────── Typography ───────────────────────

export type FontPair = {
  display: string;
  body: string;
  pptxDisplay: string;
  pptxBody: string;
  letterSpacing?: string;
  titleWeight?: number;
};

export const FONT_PAIRS: Record<string, FontPair> = {
  classic:   { display: "Georgia, 'David Libre', serif", body: "'David Libre', Georgia, serif", pptxDisplay: "Georgia", pptxBody: "David", titleWeight: 700 },
  modern:    { display: "'Helvetica Neue', Arial, sans-serif", body: "'Helvetica Neue', Arial, sans-serif", pptxDisplay: "Calibri", pptxBody: "Calibri", titleWeight: 700 },
  editorial: { display: "Georgia, 'Frank Ruhl Libre', serif", body: "'Frank Ruhl Libre', Georgia, serif", pptxDisplay: "Georgia", pptxBody: "Frank Ruhl Libre", titleWeight: 700 },
  tech:      { display: "'Helvetica Neue', system-ui, sans-serif", body: "'Helvetica Neue', system-ui, sans-serif", pptxDisplay: "Calibri", pptxBody: "Calibri", letterSpacing: "-0.02em", titleWeight: 800 },
  elegant:   { display: "'Frank Ruhl Libre', Georgia, serif", body: "'Heebo', Arial, sans-serif", pptxDisplay: "Frank Ruhl Libre", pptxBody: "Heebo", titleWeight: 600 },
  bold:      { display: "'Heebo', Arial, sans-serif", body: "'Heebo', Arial, sans-serif", pptxDisplay: "Heebo", pptxBody: "Heebo", letterSpacing: "-0.01em", titleWeight: 900 },
  refined:   { display: "'Frank Ruhl Libre', serif", body: "'David Libre', serif", pptxDisplay: "Frank Ruhl Libre", pptxBody: "David", titleWeight: 600 },
  utility:   { display: "'Heebo', system-ui, sans-serif", body: "'David Libre', serif", pptxDisplay: "Heebo", pptxBody: "David", titleWeight: 700 },
};

export type FontPairId = keyof typeof FONT_PAIRS;

// ─────────────────────── Theme spec ───────────────────────

// Premium design systems (richer than the cover×content combinator).
// When `design` is set, the SlideView bypasses the cover/content router
// and renders via the named design — e.g. "editorial" routes every
// slide through designs/Editorial.tsx, which still reads palette+font
// from this theme so palette swaps still work.
export type DesignSystem = "editorial";

export type DeckTheme = {
  id: string;
  name_he: string;
  name_en: string;
  palette: PaletteId;
  cover: CoverStyle;
  content: ContentStyle;
  font: FontPairId;
  titleScale?: number;
  bodyScale?: number;
  design?: DesignSystem;
};

// ─────────────────────── The 55 themes ───────────────────────

export const DECK_THEMES: DeckTheme[] = [
  // 1–8: Corporate / classic
  { id: "navy-classic",      name_he: "תאגידי קלאסי",       name_en: "Corporate Classic",     palette: "corporate-navy",  cover: "left-bar-strong",   content: "classic-top",   font: "classic" },
  { id: "navy-magazine",     name_he: "תאגידי עריכה",       name_en: "Corporate Editorial",   palette: "corporate-navy",  cover: "horizon-line",       content: "magazine",      font: "editorial" },
  { id: "navy-numbered",     name_he: "תאגידי ממוספר",      name_en: "Corporate Numbered",    palette: "corporate-navy",  cover: "centered-bold",      content: "numbered-list", font: "modern" },
  { id: "navy-block",        name_he: "תאגידי בלוק",        name_en: "Corporate Block",       palette: "corporate-navy",  cover: "duotone-block",      content: "header-block",  font: "bold" },
  { id: "navy-frame",        name_he: "תאגידי ממוסגר",      name_en: "Corporate Framed",      palette: "corporate-navy",  cover: "framed-thin",        content: "framed",        font: "refined" },
  { id: "navy-split",        name_he: "תאגידי מפוצל",       name_en: "Corporate Split",       palette: "corporate-navy",  cover: "split-half",         content: "half-color",    font: "modern" },
  { id: "navy-side",         name_he: "תאגידי פס צד",       name_en: "Corporate Side Band",   palette: "corporate-navy",  cover: "stripes-side",       content: "side-band",     font: "classic" },
  { id: "navy-two-col",      name_he: "תאגידי שתי עמודות",  name_en: "Corporate Two-Column",  palette: "corporate-navy",  cover: "label-strip",        content: "two-column",    font: "modern" },

  // 9–14: Midnight violet
  { id: "violet-card",       name_he: "סגול-כרטיס",          name_en: "Violet Card",           palette: "midnight-violet", cover: "card-center",        content: "card-stack",    font: "modern" },
  { id: "violet-circle",     name_he: "סגול-עיגול",          name_en: "Violet Circle",         palette: "midnight-violet", cover: "circle-accent",      content: "circle-bullets",font: "elegant" },
  { id: "violet-gradient",   name_he: "סגול-גרדיאנט",        name_en: "Violet Gradient",       palette: "midnight-violet", cover: "gradient-diagonal",  content: "minimal-line",  font: "modern" },
  { id: "violet-corner",     name_he: "סגול-פינתי",          name_en: "Violet Corner",         palette: "midnight-violet", cover: "geometric-corner",   content: "corner-accent", font: "bold" },
  { id: "violet-stripe",     name_he: "סגול-פס",             name_en: "Violet Stripe",         palette: "midnight-violet", cover: "stripes-side",       content: "stripe-cards",  font: "modern" },
  { id: "violet-magazine",   name_he: "סגול-עריכה",          name_en: "Violet Editorial",      palette: "midnight-violet", cover: "outlined-title",     content: "magazine",      font: "editorial" },

  // 15–19: Deep forest
  { id: "forest-classic",    name_he: "יער-קלאסי",           name_en: "Forest Classic",        palette: "deep-forest",     cover: "left-bar-strong",    content: "classic-top",   font: "classic" },
  { id: "forest-dot",        name_he: "יער-נקודות",          name_en: "Forest Dots",           palette: "deep-forest",     cover: "geometric-corner",   content: "dot-grid",      font: "modern" },
  { id: "forest-band",       name_he: "יער-פס",              name_en: "Forest Band",           palette: "deep-forest",     cover: "horizon-line",       content: "footer-band",   font: "elegant" },
  { id: "forest-circle",     name_he: "יער-עיגול",           name_en: "Forest Circle",         palette: "deep-forest",     cover: "circle-accent",      content: "circle-bullets",font: "refined" },
  { id: "forest-num",        name_he: "יער-ממוספר",          name_en: "Forest Numbered",       palette: "deep-forest",     cover: "big-number-corner",  content: "numbered-list", font: "bold" },

  // 20–22: Wine
  { id: "wine-elegant",      name_he: "יין-אלגנטי",          name_en: "Wine Elegant",          palette: "wine",            cover: "underline-title",    content: "left-rule",     font: "editorial" },
  { id: "wine-frame",        name_he: "יין-מסגרת",           name_en: "Wine Framed",           palette: "wine",            cover: "framed-thin",        content: "framed",        font: "refined" },
  { id: "wine-magazine",     name_he: "יין-עריכה",           name_en: "Wine Editorial",        palette: "wine",            cover: "outlined-title",     content: "magazine",      font: "editorial" },

  // 23–28: Obsidian
  { id: "obsidian-bold",     name_he: "אבסידיאן-בולט",       name_en: "Obsidian Bold",         palette: "obsidian",        cover: "centered-bold",      content: "header-block",  font: "bold" },
  { id: "obsidian-big",      name_he: "אבסידיאן-מספר",       name_en: "Obsidian Big Number",   palette: "obsidian",        cover: "big-number-corner",  content: "numbered-list", font: "bold" },
  { id: "obsidian-outline",  name_he: "אבסידיאן-קווי",       name_en: "Obsidian Outline",      palette: "obsidian",        cover: "outlined-title",     content: "minimal-line",  font: "modern" },
  { id: "obsidian-stripe",   name_he: "אבסידיאן-פס",         name_en: "Obsidian Stripe",       palette: "obsidian",        cover: "stripes-side",       content: "stripe-cards",  font: "tech" },
  { id: "obsidian-card",     name_he: "אבסידיאן-כרטיס",      name_en: "Obsidian Card",         palette: "obsidian",        cover: "card-center",        content: "card-stack",    font: "modern" },
  { id: "obsidian-circle",   name_he: "אבסידיאן-עיגול",      name_en: "Obsidian Circle",       palette: "obsidian",        cover: "circle-accent",      content: "circle-bullets",font: "bold" },

  // 29–33: Tech cyan
  { id: "tech-grid",         name_he: "טכנו-רשת",            name_en: "Tech Grid",             palette: "tech-cyan",       cover: "geometric-corner",   content: "dot-grid",      font: "tech" },
  { id: "tech-stripe",       name_he: "טכנו-פס",             name_en: "Tech Stripe",           palette: "tech-cyan",       cover: "stripes-side",       content: "side-band",     font: "tech" },
  { id: "tech-mono",         name_he: "טכנו-מונו",           name_en: "Tech Mono",             palette: "tech-cyan",       cover: "minimal-bottom",     content: "minimal-line",  font: "tech" },
  { id: "tech-block",        name_he: "טכנו-בלוק",           name_en: "Tech Block",            palette: "tech-cyan",       cover: "duotone-block",      content: "header-block",  font: "tech" },
  { id: "tech-corner",       name_he: "טכנו-פינה",           name_en: "Tech Corner",           palette: "tech-cyan",       cover: "geometric-corner",   content: "corner-accent", font: "tech" },

  // 34–37: Muted slate
  { id: "slate-magazine",    name_he: "אפור-עריכה",          name_en: "Slate Editorial",       palette: "muted-slate",     cover: "horizon-line",       content: "magazine",      font: "editorial" },
  { id: "slate-card",        name_he: "אפור-כרטיס",          name_en: "Slate Card",            palette: "muted-slate",     cover: "card-center",        content: "card-stack",    font: "modern" },
  { id: "slate-two-col",     name_he: "אפור-שתי עמודות",     name_en: "Slate Two-Column",      palette: "muted-slate",     cover: "centered-bold",      content: "two-column",    font: "modern" },
  { id: "slate-circle",      name_he: "אפור-עיגול",          name_en: "Slate Circle",          palette: "muted-slate",     cover: "circle-accent",      content: "circle-bullets",font: "refined" },

  // 38–40: Soft cream
  { id: "cream-classic",     name_he: "קרם-קלאסי",           name_en: "Cream Classic",         palette: "soft-cream",      cover: "left-bar-strong",    content: "classic-top",   font: "classic" },
  { id: "cream-editorial",   name_he: "קרם-עריכה",           name_en: "Cream Editorial",       palette: "soft-cream",      cover: "underline-title",    content: "magazine",      font: "editorial" },
  { id: "cream-frame",       name_he: "קרם-מסגרת",           name_en: "Cream Framed",          palette: "soft-cream",      cover: "framed-thin",        content: "framed",        font: "refined" },

  // 41–44: Minimal paper
  { id: "paper-minimal",     name_he: "נייר-מינימלי",        name_en: "Paper Minimal",         palette: "minimal-paper",   cover: "minimal-bottom",     content: "minimal-line",  font: "modern" },
  { id: "paper-magazine",    name_he: "נייר-עריכה",          name_en: "Paper Editorial",       palette: "minimal-paper",   cover: "underline-title",    content: "magazine",      font: "editorial" },
  { id: "paper-num",         name_he: "נייר-ממוספר",         name_en: "Paper Numbered",        palette: "minimal-paper",   cover: "big-number-corner",  content: "numbered-list", font: "bold" },
  { id: "paper-frame",       name_he: "נייר-מסגרת",          name_en: "Paper Framed",          palette: "minimal-paper",   cover: "framed-thin",        content: "framed",        font: "refined" },

  // 45–47: Warm terracotta
  { id: "terra-bold",        name_he: "טראקוטה-בולט",        name_en: "Terracotta Bold",       palette: "warm-terracotta", cover: "centered-bold",      content: "header-block",  font: "bold" },
  { id: "terra-magazine",    name_he: "טראקוטה-עריכה",       name_en: "Terracotta Editorial",  palette: "warm-terracotta", cover: "horizon-line",       content: "magazine",      font: "editorial" },
  { id: "terra-card",        name_he: "טראקוטה-כרטיס",       name_en: "Terracotta Card",       palette: "warm-terracotta", cover: "card-center",        content: "card-stack",    font: "modern" },

  // 48–50: Fresh green
  { id: "green-classic",     name_he: "ירוק-קלאסי",          name_en: "Green Classic",         palette: "fresh-green",     cover: "left-bar-strong",    content: "classic-top",   font: "classic" },
  { id: "green-dot",         name_he: "ירוק-נקודות",         name_en: "Green Dots",            palette: "fresh-green",     cover: "geometric-corner",   content: "dot-grid",      font: "modern" },
  { id: "green-circle",      name_he: "ירוק-עיגול",          name_en: "Green Circle",          palette: "fresh-green",     cover: "circle-accent",      content: "circle-bullets",font: "refined" },

  // 51–55: Blush, mono, earth, arctic, sunset
  { id: "blush-elegant",     name_he: "ורוד-אלגנטי",         name_en: "Blush Elegant",         palette: "blush",           cover: "underline-title",    content: "left-rule",     font: "elegant" },
  { id: "mono-bold",         name_he: "מונוכרום-בולט",       name_en: "Mono Bold",             palette: "monochrome",      cover: "outlined-title",     content: "stripe-cards",  font: "bold" },
  { id: "earth-classic",     name_he: "אדמה-קלאסי",          name_en: "Earth Classic",         palette: "earth",           cover: "left-bar-strong",    content: "classic-top",   font: "classic" },
  { id: "arctic-card",       name_he: "ארקטי-כרטיס",         name_en: "Arctic Card",           palette: "arctic",          cover: "card-center",        content: "card-stack",    font: "modern" },
  { id: "sunset-bold",       name_he: "שקיעה-בולט",          name_en: "Sunset Bold",           palette: "sunset",          cover: "centered-bold",      content: "header-block",  font: "bold" },

  // Premium design — Editorial (magazine-grade typography, palette-aware).
  // cover/content fields are unused when `design` is set but kept for type
  // compatibility.
  { id: "editorial-navy",    name_he: "Editorial · נייבי",    name_en: "Editorial · Navy",      palette: "corporate-navy",  cover: "minimal-bottom",     content: "minimal-line",  font: "editorial", design: "editorial" },
  { id: "editorial-cream",   name_he: "Editorial · קרם",      name_en: "Editorial · Cream",     palette: "soft-cream",      cover: "minimal-bottom",     content: "minimal-line",  font: "editorial", design: "editorial" },
  { id: "editorial-forest",  name_he: "Editorial · יער",      name_en: "Editorial · Forest",    palette: "deep-forest",     cover: "minimal-bottom",     content: "minimal-line",  font: "editorial", design: "editorial" },
  { id: "editorial-wine",    name_he: "Editorial · יין",      name_en: "Editorial · Wine",      palette: "wine",            cover: "minimal-bottom",     content: "minimal-line",  font: "editorial", design: "editorial" },
  { id: "editorial-mono",    name_he: "Editorial · מונוכרום", name_en: "Editorial · Mono",      palette: "monochrome",      cover: "minimal-bottom",     content: "minimal-line",  font: "editorial", design: "editorial" },
];

// Convenience accessors

export function getTheme(id: string): DeckTheme {
  return DECK_THEMES.find((t) => t.id === id) ?? DECK_THEMES[0];
}

export function getPalette(p: PaletteId): Palette {
  return PALETTES[p];
}

export function getFont(id: FontPairId): FontPair {
  return FONT_PAIRS[id];
}

// Convert "#abcdef" → "abcdef" (no hash) for pptxgenjs
export function noHash(c: string): string {
  return c.startsWith("#") ? c.slice(1) : c;
}
